import { Aside } from "aside.slint";
import { List } from "list.slint";
import { VDivider } from "divider.slint";
import { Status, EntryData, DownloadConfig, GeneralConfig } from "types.slint";
import { TaskDialog } from "task-dialog.slint";
import { Settings } from "settings.slint";
import { TaskDialog } from "task-dialog.slint";
import { Theme } from "theme.slint";
import { Logic } from "logic.slint";

export {
    TaskDialog,
    Logic
}

export component MainWindow inherits Window {
    title: "fast-down v" + version + (admin ? " (管理员)" : "");
    icon: Theme.app-icon;
    min-width: 800px;
    min-height: 600px;
    default-font-family: Theme.font-family;

    callback browse_folder();

    in property <string> version;
    in property <bool> admin;
    in-out property <DownloadConfig> download_config;
    in-out property <GeneralConfig> general_config;
    public function set_save_dir(dir: string) {
        download_config.save-dir = dir;
    }

    property <[EntryData]> active_list:
            aside.current_page == 0 ? all_list : aside.current_page == 1 ? running_list : aside.current_page == 2 ? waiting_list : aside.current_page == 3 ? paused_list : aside.current_page == 4 ? completed_list : error_list;

    in property <[EntryData]> all_list;
    in property <[EntryData]> running_list;
    in property <[EntryData]> waiting_list;
    in property <[EntryData]> paused_list;
    in property <[EntryData]> completed_list;
    in property <[EntryData]> error_list;

    HorizontalLayout {
        aside := Aside {
            running_count: running_list.length;
            waiting_count: waiting_list.length;
            paused_count: paused_list.length;
            completed_count: completed_list.length;
            error_count: error_list.length;
        }

        VDivider { }

        if aside.current_page < 6: List {
            list: active_list;
            only-remove-completed: aside.current_page == 0;
            start_all => {
                Logic.start_all(active_list);
            }
            pause_all => {
                Logic.pause_all(active_list);
            }
            remove_all => {
                Logic.remove_all(aside.current_page == 0 ? completed_list : active_list);
            }
        }
        if aside.current_page == 6: Settings {
            download_config <=> download_config;
            general_config <=> general_config;
            browse_folder => {
                browse_folder()
            }
        }
    }
}
