import { Aside } from "aside.slint";
import { List } from "list.slint";
import { VDivider } from "divider.slint";
import { Status, EntryData } from "entry.slint";
import { TaskDialog } from "task-dialog.slint";
import { Settings, Config } from "settings.slint";
import { TaskDialog } from "task-dialog.slint";
import { Theme } from "theme.slint";

export {
    TaskDialog,
}

export component MainWindow inherits Window {
    title: "fast-down v" + version;
    icon: Theme.app-icon;
    min-width: 800px;
    min-height: 600px;
    default-font-family: Theme.font-family;

    callback start_entry(int);
    callback pause_entry(int);
    callback detail_entry(int);
    callback open_entry(string);
    callback open_folder_entry(string);
    callback remove_entry(int);

    callback add_task();
    callback exit();
    callback browse_folder();
    callback config_change(Config);
    callback view_log();

    callback start_all([EntryData]);
    callback pause_all([EntryData]);
    callback remove_all([EntryData]);

    in property <string> version;
    in-out property <Config> config;
    public function set_save_dir(dir: string) {
        config.save-dir = dir;
    }

    property <[EntryData]> active_list:
            aside.current_page == 0 ? all_list : aside.current_page == 1 ? running_list : aside.current_page == 2 ? waiting_list : aside.current_page == 3 ? paused_list : aside.current_page == 4 ? completed_list : error_list;

    in property <[EntryData]> all_list;
    in property <[EntryData]> running_list;
    in property <[EntryData]> waiting_list;
    in property <[EntryData]> paused_list;
    in property <[EntryData]> completed_list;
    in property <[EntryData]> error_list;

    HorizontalLayout {
        aside := Aside {
            running_count: running_list.length;
            waiting_count: waiting_list.length;
            paused_count: paused_list.length;
            completed_count: completed_list.length;
            error_count: error_list.length;
            add_task => {
                add_task();
            }
            exit => {
                exit()
            }
        }

        VDivider { }

        if aside.current_page < 6: List {
            list: active_list;
            start_all => {
                root.start_all(active_list);
            }
            pause_all => {
                root.pause_all(active_list);
            }
            remove_all => {
                root.remove_all(active_list);
            }
            start(entry) => {
                start_entry(entry)
            }
            pause(entry) => {
                pause_entry(entry)
            }
            detail(entry) => {
                detail_entry(entry)
            }
            open(entry) => {
                open_entry(entry)
            }
            open_folder(entry) => {
                open_folder_entry(entry)
            }
            remove(entry) => {
                remove_entry(entry)
            }
        }
        if aside.current_page == 6: Settings {
            config <=> config;
            browse_folder => {
                browse_folder()
            }
            config_change(config) => {
                config_change(config)
            }
            view_log => {
                view_log()
            }
        }
    }
}
