import {
    VerticalBox,
    Button,
    HorizontalBox,
    ListView,
} from "std-widgets.slint";
import { EntryData, Entry } from "entry.slint";
import { HDivider } from "divider.slint";

export component List inherits Rectangle {
    horizontal-stretch: 1;

    in property <[EntryData]> list;
    in property <bool> only-remove-completed;
    callback start(int);
    callback pause(int);
    callback detail(int);
    callback open(string);
    callback open_folder(string);
    callback remove(int);

    callback start_all();
    callback pause_all();
    callback remove_all();

    VerticalLayout {
        VerticalLayout {
            vertical-stretch: 0;
            HorizontalBox {
                alignment: LayoutAlignment.start;
                Button {
                    text: "开始列表";
                    clicked => {
                        start_all()
                    }
                }

                Button {
                    text: "暂停列表";
                    clicked => {
                        pause_all()
                    }
                }

                Button {
                    text: only-remove-completed ? "移除已完成" : "清空列表";
                    clicked => {
                        remove_all()
                    }
                }
            }

            HDivider { }
        }

        ListView {
            mouse-drag-pan-enabled: true;

            for entry[i] in list: VerticalLayout {
                Entry {
                    data: entry;
                    start => {
                        start(entry.gid)
                    }
                    pause => {
                        pause(entry.gid)
                    }
                    detail => {
                        detail(entry.gid)
                    }
                    open => {
                        open(entry.path)
                    }
                    open_folder => {
                        open_folder(entry.path)
                    }
                    remove => {
                        remove(entry.gid)
                    }
                }

                HDivider { }
            }
        }
    }
}
