import {
    Button,
    LineEdit,
    VerticalBox,
    ScrollView,
    HorizontalBox,
    StandardButton,
    TextEdit,
    CheckBox,
    ComboBox,
    Switch,
} from "std-widgets.slint";
import { HDivider } from "divider.slint";
import { NoScrollSpinBox } from "my-spin-box.slint";
import { Header1, Header2 } from "headers.slint";

export struct DownloadConfig {
    save_dir: string,
    threads: int,
    proxy: string,
    headers: string,
    min_chunk_size: int,
    write_buffer_size: int,
    write_queue_cap: int,
    retry_gap_ms: int,
    pull_timeout_ms: int,
    accept_invalid_certs: bool,
    accept_invalid_hostnames: bool,
    ips: string,
    max_speculative: int,
    write_method: int,
    retry_times: int,
    chunk_window: int,
}
export struct GeneralConfig {
    max_concurrency: int,
    auto_start: bool,
}

export component Settings inherits VerticalLayout {
    horizontal-stretch: 1;

    in-out property <DownloadConfig> download_config;
    in-out property <GeneralConfig> general_config;

    callback browse_folder();
    callback config_change(DownloadConfig, GeneralConfig);
    callback view_log();

    changed download_config => {
        config_change(download_config, general_config);
    }

    changed general_config => {
        config_change(download_config, general_config);
    }

    HorizontalBox {
        Header1 {
            text: "设置";
        }
    }

    HDivider { }

    ScrollView {
        VerticalBox {
            padding: 16px;
            alignment: LayoutAlignment.start;

            Header2 {
                text: "基础选项";
            }

            Text {
                text: "保存文件夹";
            }

            HorizontalBox {
                padding: 0px;

                LineEdit {
                    text <=> download_config.save-dir;
                    placeholder-text: "留空默认为下载目录";
                }

                Button {
                    text: "浏览";
                    clicked => {
                        browse_folder();
                    }
                }
            }

            HorizontalBox {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "线程数";
                    }

                    NoScrollSpinBox {
                        minimum: 1;
                        value <=> download_config.threads;
                    }
                }

                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "并发任务数";
                    }

                    NoScrollSpinBox {
                        minimum: 1;
                        value <=> general_config.max-concurrency;
                    }
                }
            }

            Text {
                text: "代理";
            }

            LineEdit {
                text <=> download_config.proxy;
                placeholder-text: "留空为系统代理，输入 null 为不使用代理";
            }

            Text {
                text: "请求头";
            }

            TextEdit {
                text <=> download_config.headers;
                min-height: 150px;
                placeholder-text: "Cookie: value\nUser-Agent: Mozilla/5.0";
            }

            HDivider { }

            Header2 {
                text: "高级选项";
            }

            HorizontalBox {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "最小分片大小 (字节)";
                    }

                    NoScrollSpinBox {
                        minimum: 1;
                        value <=> download_config.min-chunk-size;
                    }
                }

                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "写入缓冲区大小 (字节)";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.write-buffer-size;
                    }
                }
            }

            HorizontalBox {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "投机线程数";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.max-speculative;
                    }
                }

                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "写入队列大小";
                    }

                    NoScrollSpinBox {
                        minimum: 1;
                        value <=> download_config.write-queue-cap;
                    }
                }
            }

            HorizontalBox {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "重试间隔 (毫秒)";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.retry-gap-ms;
                    }
                }

                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "拉取超时 (毫秒)";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.pull-timeout-ms;
                    }
                }
            }

            HorizontalBox {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "重试次数";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.retry-times;
                    }
                }

                VerticalBox {
                    padding: 0px;
                    Text {
                        text: "块平滑窗口";
                    }

                    NoScrollSpinBox {
                        value <=> download_config.chunk-window;
                    }
                }
            }

            HorizontalBox {
                padding: 0px;
                CheckBox {
                    text: "接受无效证书";
                    horizontal-stretch: 1;
                    checked <=> download_config.accept-invalid-certs;
                }

                CheckBox {
                    text: "接受无效主机";
                    horizontal-stretch: 1;
                    checked <=> download_config.accept-invalid-hostnames;
                }
            }

            CheckBox {
                text: "开机自启动";
                horizontal-stretch: 1;
                checked <=> general_config.auto-start;
            }

            Text {
                text: "写入方法";
            }

            ComboBox {
                model: ["内存映射文件 (推荐)", "标准库 (兼容性好)"];
                current-index <=> download_config.write-method;
            }

            Text {
                text: "网卡池";
            }

            TextEdit {
                text <=> download_config.ips;
                min-height: 150px;
                placeholder-text: "192.168.1.8\n192.168.1.9\n留空则使用默认网卡发送请求";
            }

            Button {
                text: "查看日志";
                clicked => {
                    view_log()
                }
            }
        }
    }
}
