import {
    Button,
    LineEdit,
    ScrollView,
    StandardButton,
    TextEdit,
    CheckBox,
    SpinBox,
    GridBox,
    ComboBox,
} from "std-widgets.slint";
import { HDivider } from "divider.slint";
import { NoScrollSpinBox } from "my-spin-box.slint";
import { DownloadConfig } from "settings.slint";
import { Theme } from "theme.slint";
import { Header2 } from "headers.slint";
import { Help } from "info.slint";

export enum DialogType {
    AddTask,
    EditTask,
}

export component TaskDialog inherits Window {
    title: type == DialogType.AddTask ? "添加任务" : "编辑任务";
    icon: Theme.app-icon;
    min-width: 500px;
    min-height: 500px;
    default-font-family: Theme.font-family;

    in property <DialogType> type;
    in property <bool> show-bg-download;
    in-out property <string> urls;
    in-out property <DownloadConfig> download_config;

    callback confirm(string, DownloadConfig, bool);
    callback browse_folder();
    callback canceled();

    public function set_save_dir(dir: string) {
        download_config.save-dir = dir;
    }

    VerticalLayout {
        ScrollView {
            VerticalLayout {
                padding: 16px;
                spacing: 8px;
                Header2 {
                    text: "基础选项";
                }

                Text {
                    text: "下载链接";
                }

                TextEdit {
                    text <=> urls;
                    min-height: 150px;
                    placeholder-text: "https://example.com/file1.zip\nhttp://example.com/file2.zip";
                }

                Text {
                    text: "保存文件夹";
                }

                HorizontalLayout {
                    spacing: 8px;

                    LineEdit {
                        text <=> download_config.save-dir;
                        placeholder-text: "留空默认为下载目录";
                    }

                    Button {
                        text: "浏览";
                        clicked => {
                            browse_folder();
                        }
                    }
                }

                Text {
                    text: "自定义文件名";
                }

                LineEdit {
                    text <=> download_config.file-name;
                    placeholder-text: "留空默认为自动获取";
                }

                Help {
                    tooltip: "线程越多不意味着越快\n推荐值 32 / 16 / 8";
                    alignment: left;

                    Text {
                        text: "线程数";
                    }
                }

                NoScrollSpinBox {
                    minimum: 1;
                    value <=> download_config.threads;
                }

                HDivider { }

                Header2 {
                    text: "高级选项";
                }

                Text {
                    text: "请求头";
                }

                TextEdit {
                    text <=> download_config.headers;
                    min-height: 150px;
                    placeholder-text: "Cookie: value\nUser-Agent: Mozilla/5.0";
                }

                Help {
                    tooltip: "支持 https、http、socks5 代理";
                    alignment: left;

                    Text {
                        text: "代理";
                    }
                }

                LineEdit {
                    text <=> download_config.proxy;
                    placeholder-text: "留空为系统代理，输入 null 为不使用代理";
                }

                HorizontalLayout {
                    spacing: 8px;
                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "任务窃取时会保证每个分片的大小 ≥ 该值\n推荐值 8 MiB\n分片太小容易造成强烈竞争\n当无法分片的时候会进入冗余竞争模式";

                            Text {
                                text: "最小分片大小 (字节)";
                            }
                        }

                        NoScrollSpinBox {
                            minimum: 1;
                            value <=> download_config.min-chunk-size;
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "有利于将随机写入转换为顺序写入，提高写入速度\n推荐值 16 MiB\n该值越大越好";
                            alignment: right;

                            Text {
                                text: "写入缓冲区大小 (字节)";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.write-buffer-size;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 8px;
                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "当分片大小太小后，进入冗余竞争模式。\n该值决定了最多有多少个线程在同一分片上竞争下载，以解决下载卡进度 99% 的问题\n推荐值 3";
                            alignment: left;

                            Text {
                                text: "冗余线程数";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.max-speculative;
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "如果下载线程太快，填满了写入队列，会触发压背，降低下载速度，防止内存占用过大\n推荐值 10240\n如果内存占用过大，应该调小该值";

                            Text {
                                text: "写入队列大小";
                            }
                        }

                        NoScrollSpinBox {
                            minimum: 1;
                            value <=> download_config.write-queue-cap;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 8px;
                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "请求失败后的默认重试间隔\n推荐值 500ms\n如果服务器返回中有 Retry-After 头，则遵循服务器返回的设定";
                            alignment: left;

                            Text {
                                text: "重试间隔 (毫秒)";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.retry-gap-ms;
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "推荐值 5000ms\n请求发出后，接收字节中，如果在 pull_timeout 这一段时间内一个字节也没收到，则中断连接，重新请求。\n有利于触发 TCP 重新检测拥塞状态，提高下载速度";

                            Text {
                                text: "拉取超时 (毫秒)";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.pull-timeout-ms;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 8px;
                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "设置获取元数据的重试次数\n推荐值 10\n注意，这不是下载中的重试次数，下载中会无限重试";
                            alignment: left;

                            Text {
                                text: "重试次数";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.retry-times;
                        }
                    }

                    VerticalLayout {
                        spacing: 8px;

                        Help {
                            tooltip: "推荐值 8 KiB\n它会过滤掉小于该值的小空洞，并合成一个大范围，以减小 HTTP 请求数量";

                            Text {
                                text: "块平滑窗口";
                            }
                        }

                        NoScrollSpinBox {
                            value <=> download_config.chunk-window;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 8px;

                    Help {
                        tooltip: "不安全，极度不建议开启";

                        CheckBox {
                            text: "接受无效证书";
                            horizontal-stretch: 1;
                            checked <=> download_config.accept-invalid-certs;
                        }
                    }

                    Help {
                        tooltip: "不安全，极度不建议开启";

                        CheckBox {
                            text: "接受无效主机";
                            horizontal-stretch: 1;
                            checked <=> download_config.accept-invalid-hostnames;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 8px;

                    Help {
                        tooltip: "在下载前预分配文件大小\n如果你的设备支持快速分配，那么强烈推荐开启此选项";
                        alignment: left;

                        CheckBox {
                            text: "文件预分配　";
                            checked <=> download_config.pre-allocate;
                        }
                    }

                    Help {
                        tooltip: "开启后会把 URL 的 path 提取并自动创建目录";
                        alignment: right;

                        CheckBox {
                            text: "保持目录结构";
                            horizontal-stretch: 1;
                            checked <=> download_config.keep-folder-structure;
                        }
                    }
                }

                Text {
                    text: "写入方法";
                }

                ComboBox {
                    model: ["内存映射文件 (推荐)", "标准库 (兼容性好)"];
                    current-index <=> download_config.write-method;
                }

                Help {
                    tooltip: "使用哪些地址来发送请求\n如果你有多个网卡可用，可以填写他们的对外 IP 地址，请求会在这些 IP 地址上轮换，下载不一定会更快，还会与 VPN 软件冲突";
                    alignment: left;

                    Text {
                        text: "网卡池";
                    }
                }

                TextEdit {
                    text <=> download_config.ips;
                    min-height: 150px;
                    placeholder-text: "192.168.1.8\n192.168.1.9\n留空则使用默认网卡发送请求";
                }
            }
        }

        HorizontalLayout {
            padding: 8px;
            spacing: 8px;
            alignment: LayoutAlignment.end;
            Button {
                text: type == DialogType.AddTask ? "立刻下载" : "保存";
                primary: true;
                clicked => {
                    confirm(urls, download_config, false);
                }
            }

            if show-bg-download && type == DialogType.AddTask:  Button {
                text: "后台下载";
                clicked => {
                    confirm(urls, download_config, true);
                }
            }

            Button {
                text: "取消";
                clicked => {
                    canceled();
                }
            }
        }
    }
}
