import {
    Button,
    LineEdit,
    VerticalBox,
    ScrollView,
    HorizontalBox,
    StandardButton,
    TextEdit,
    CheckBox,
    SpinBox,
    GridBox,
    ComboBox,
} from "std-widgets.slint";
import { HDivider } from "divider.slint";
import { NoScrollSpinBox } from "my-spin-box.slint";
import { DownloadConfig } from "settings.slint";
import { Theme } from "theme.slint";
import { Header2 } from "headers.slint";

export enum DialogType {
    AddTask,
    EditTask,
}

export component TaskDialog inherits Window {
    title: type == DialogType.AddTask ? "添加任务" : "编辑任务";
    icon: Theme.app-icon;
    min-width: 500px;
    min-height: 500px;
    default-font-family: Theme.font-family;

    in property <DialogType> type;
    in-out property <string> urls;
    in-out property <DownloadConfig> download_config;

    callback confirm(string, DownloadConfig);
    callback browse_folder();
    callback canceled();

    public function set_save_dir(dir: string) {
        download_config.save-dir = dir;
    }

    VerticalLayout {
        ScrollView {
            VerticalBox {
                padding: 16px;
                Header2 {
                    text: "基础选项";
                }

                Text {
                    text: "下载链接";
                }

                TextEdit {
                    text <=> urls;
                    min-height: 150px;
                    placeholder-text: "https://example.com/file1.zip\nhttp://example.com/file2.zip";
                }

                Text {
                    text: "保存文件夹";
                }

                HorizontalBox {
                    padding: 0px;

                    LineEdit {
                        text <=> download_config.save-dir;
                        placeholder-text: "留空默认为下载目录";
                    }

                    Button {
                        text: "浏览";
                        clicked => {
                            browse_folder();
                        }
                    }
                }

                Text {
                    text: "线程数";
                }

                NoScrollSpinBox {
                    minimum: 1;
                    value <=> download_config.threads;
                }

                HDivider { }

                Header2 {
                    text: "高级选项";
                }

                Text {
                    text: "请求头";
                }

                TextEdit {
                    text <=> download_config.headers;
                    min-height: 150px;
                    placeholder-text: "Cookie: value\nUser-Agent: Mozilla/5.0";
                }

                Text {
                    text: "代理";
                }

                LineEdit {
                    text <=> download_config.proxy;
                    placeholder-text: "留空为系统代理，输入 null 为不使用代理";
                }

                HorizontalBox {
                    padding: 0px;
                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "最小分片大小 (字节)";
                        }

                        NoScrollSpinBox {
                            minimum: 1;
                            value <=> download_config.min-chunk-size;
                        }
                    }

                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "写入缓冲区大小 (字节)";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.write-buffer-size;
                        }
                    }
                }

                HorizontalBox {
                    padding: 0px;
                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "投机线程数";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.max-speculative;
                        }
                    }

                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "写入队列大小";
                        }

                        NoScrollSpinBox {
                            minimum: 1;
                            value <=> download_config.write-queue-cap;
                        }
                    }
                }

                HorizontalBox {
                    padding: 0px;
                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "重试间隔 (毫秒)";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.retry-gap-ms;
                        }
                    }

                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "拉取超时 (毫秒)";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.pull-timeout-ms;
                        }
                    }
                }

                HorizontalBox {
                    padding: 0px;
                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "重试次数";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.retry-times;
                        }
                    }

                    VerticalBox {
                        padding: 0px;
                        Text {
                            text: "块平滑窗口";
                        }

                        NoScrollSpinBox {
                            value <=> download_config.chunk-window;
                        }
                    }
                }

                HorizontalBox {
                    padding: 0px;
                    CheckBox {
                        text: "接受无效证书";
                        horizontal-stretch: 1;
                        checked <=> download_config.accept-invalid-certs;
                    }

                    CheckBox {
                        text: "接受无效主机";
                        horizontal-stretch: 1;
                        checked <=> download_config.accept-invalid-hostnames;
                    }
                }

                Text {
                    text: "写入方法";
                }

                ComboBox {
                    model: ["内存映射文件 (推荐)", "标准库 (兼容性好)"];
                    current-index <=> download_config.write-method;
                }

                Text {
                    text: "网卡池";
                }

                TextEdit {
                    text <=> download_config.ips;
                    min-height: 150px;
                    placeholder-text: "192.168.1.8\n192.168.1.9\n留空则使用默认网卡发送请求";
                }
            }
        }

        HorizontalBox {
            alignment: LayoutAlignment.end;
            Button {
                text: type == DialogType.AddTask ? "立刻下载" : "保存";
                primary: true;
                clicked => {
                    confirm(urls, download_config);
                }
            }

            Button {
                text: "取消";
                clicked => {
                    canceled();
                }
            }
        }
    }
}
