name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: build (${{ matrix.build }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - linux-aarch64
          - linux-x86_64
          - linux-i686
          - macos-aarch64
          - macos-x86_64
          - windows-x86_64
          - windows-i686
          - windows-aarch64
        include:
          - build: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
            archive-name: fast-down-linux-aarch64

          - build: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: true
            archive-name: fast-down-linux-x86_64

          - build: linux-i686
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use-cross: true
            archive-name: fast-down-linux-i686

          - build: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
            archive-name: fast-down-macos-aarch64.dmg

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
            archive-name: fast-down-macos-x86_64.dmg

          - build: windows-x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            use-cross: false
            archive-name: fast-down-windows-x86_64.exe

          - build: windows-i686
            os: windows-2022
            target: i686-pc-windows-msvc
            use-cross: false
            archive-name: fast-down-windows-i686.exe

          - build: windows-aarch64
            os: windows-2022
            target: aarch64-pc-windows-msvc
            use-cross: false
            archive-name: fast-down-windows-aarch64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install NASM
        if: startsWith(matrix.build, 'windows-')
        uses: ilammy/setup-nasm@v1

      - name: Set up QEMU
        if: matrix.build == 'linux-aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Cross
        if: matrix.use-cross
        uses: taiki-e/install-action@cross

      - name: Set up Node.js
        if: contains(matrix.build, 'macos')
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # https://github.com/sindresorhus/create-dmg
      - name: Set up create-dmg
        if: contains(matrix.build, 'macos')
        run: |
          npm install -g node-gyp
          npm install -g create-dmg

      - name: Install cargo-bundle
        if: contains(matrix.build, 'macos')
        run: cargo install cargo-bundle

      - name: Build binary
        shell: bash
        run: |
          if [ "${{ matrix.use-cross }}" == "true" ]; then
            cross build --verbose --release --target ${{ matrix.target }}
          else
            cargo build --verbose --release --target ${{ matrix.target }}
          fi
        env:
          RUST_BACKTRACE: 1

      - name: Bundle
        if: contains(matrix.build, 'macos')
        shell: bash
        run: |
          cargo bundle --release --target ${{ matrix.target }}

          if [[ "${{ contains(matrix.build, 'macos') }}" == "true" ]]; then
            cd target/${{ matrix.target }}/release/bundle/osx
            create-dmg ./FastDown.app --no-code-sign --overwrite --no-version-in-filename --dmg-title=FastDown
            mv ./FastDown.dmg ./fast-down.dmg
          fi
        env:
          RUST_BACKTRACE: 1

      - name: Prepare release file
        shell: bash
        run: |
          mkdir -p ./artifacts/

          OUTPUT="fast-down"
          if [[ "${{ matrix.build }}" == windows-* ]]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          if [[ "${{ matrix.build }}" == macos-* ]]; then
            OUTPUT="bundle/osx/${OUTPUT}.dmg"
          fi

          cp "target/${{ matrix.target }}/release/${OUTPUT}" "./artifacts/${{ matrix.archive-name }}"
          echo "ASSET_PATH=./artifacts/${{ matrix.archive-name }}" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build }}
          path: ${{ env.ASSET_PATH }}
          retention-days: 1

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./all-artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./all-artifacts/*
          generate_release_notes: true
