name: publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - linux-arm64
          - linux-64bit
          - macos-arm64
          - macos-64bit
          - windows-64bit
          - windows-32bit
          - windows-arm64
        include:
          - build: linux-arm64
            os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
            archive-name: fast-down-linux-arm64
          - build: linux-64bit
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
            archive-name: fast-down-linux-64bit
          - build: macos-arm64
            os: macos-13
            target: aarch64-apple-darwin
            archive-name: fast-down-macos-arm64
          - build: macos-64bit
            os: macos-13
            target: x86_64-apple-darwin
            archive-name: fast-down-macos-64bit
          - build: windows-64bit
            os: windows-2022
            target: x86_64-pc-windows-msvc
            archive-name: fast-down-windows-64bit
          - build: windows-32bit
            os: windows-2022
            target: i686-pc-windows-msvc
            archive-name: fast-down-windows-32bit
          - build: windows-arm64
            os: windows-11-arm
            target: aarch64-pc-windows-msvc
            archive-name: fast-down-windows-arm64
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: install dependencies (linux only)
        if: contains(matrix.build, 'linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Configure sccache-cache
        uses: mozilla-actions /sccache-action@v0.0.9
        if: matrix.build != 'windows-arm64'
      - name: Set Rust Caching Env
        if: matrix.build != 'windows-arm64'
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: fast-down-v__VERSION__
          releaseName: "fast-down v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          updaterJsonPreferNsis: true
          args: "--target ${{ matrix.target }}"
